apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-persistent-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: "portworx"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
